## Assignment-1

In [33]:
import numpy as np
import numpy.linalg as LA

### Question -1

#### 1. Matrix Operation
Perform the following operations on the given matrices: <br>
A=[[2    -1], [​0    3​]] <br>
B=[[1   ​ 2], [-3      4​]] <br>
a. A+B <br>
b. AB  <br>
c. 3A−2B 

In [34]:
A = np.array([[2,-1],[0,3]])
B = np.array([[1,2],[-3,4]])

print(A + B)
print("-"*15)
print(A * B)
print("-"*15)
print(3*A - 2*B)

[[ 3  1]
 [-3  7]]
---------------
[[ 2 -2]
 [ 0 12]]
---------------
[[ 4 -7]
 [ 6  1]]


### Question -2

#### 2. Determinants and Inverses  

<li>Find the determinant of A. </li>
<li> whether A is invertible. If yes, calculate A−1. </li>

In [35]:
determinant = np.linalg.det(A)
if(determinant != 0):
    print("Inverse: ",LA.inv(A))
    print("\nDeterminant : ",determinant)
else:
    print("Unable to Calculate Determinant")

Inverse:  [[0.5        0.16666667]
 [0.         0.33333333]]

Determinant :  6.0


### Question -3

<li>Compute the eigenvalues and eigenvectors of the matrix: <br>
C=[[4    1], [​−2       1]​] </li>

In [36]:
C = np.array([[4,1],[-2,1]])
eigen_val , eigen_vec = LA.eig(C)
print(eigen_val)
print("-"*20,"\n")
print(eigen_vec)

[3. 2.]
-------------------- 

[[ 0.70710678 -0.4472136 ]
 [-0.70710678  0.89442719]]


### Question -4

You are given a dataset of cars with the following features:

Number of cylinders (x1​)Engine size in liters (x2​)Horsepower (x3)

<b>
car 1:
x1: 4
x2:  1.5
x3: 100
and price: 20

car 2:
x1: 6
x2:  2.0
x3: 150
and price: 30

Then, find the price of a car 3 with features
x1: 8
x2:  3.0
x3: 200
price:? </b>

Hints:
1. Represent the given dataset as a matrix equation X.T*β=y, where X is the feature matrix, β is the coefficient vector, and y is the price vector  
2. Compute β (the coefficients) using the normal equation:
β=(X.T * X)^−1  X.T y

where,
X.T --> transpose matrix

In [37]:
X = np.array([[4,1.5,100],[6,2.0,150]])
X_req = np.array([8,3.0,200])
Y = np.array([20,30])
beta = LA.pinv(X.T @ X) @ (X.T @ Y)
new_price = X_req @ beta
print("Predicted price : ",new_price)


Predicted price :  40.00000000000283
